defmodule Craftplan.Repo.Migrations.UpdateOrderStatusEnum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders_orders) do
      modify :status, :text, default: "pending"
    end
  end

  def down do
    alter table(:orders_orders) do
      modify :status, :text, default: "unconfirmed"
    end
  end
end
