defmodule Craftplan.Repo.Migrations.RemoveCustomerTypeAndAddresses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_customers) do
      remove :shipping_address
      remove :billing_address
      remove :type
    end
  end

  def down do
    alter table(:crm_customers) do
      add :type, :text, null: false
      add :billing_address, :map
      add :shipping_address, :map
    end
  end
end
