defmodule Craftplan.Repo.Migrations.AddActiveToCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_categories) do
      add :active, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:catalog_categories) do
      remove :active
    end
  end
end
