defmodule Craftplan.Repo.Migrations.RefactorMaterialFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inventory_materials) do
      remove :maximum_stock
      remove :minimum_stock
      remove :price
      remove :sku
      modify :unit, :text, null: true, default: "piece"
      add :color, :text
      add :quantity, :decimal
      add :extra_description, :text
    end

    drop_if_exists unique_index(:inventory_materials, [:sku],
                     name: "inventory_materials_sku_index"
                   )
  end

  def down do
    create unique_index(:inventory_materials, [:sku], name: "inventory_materials_sku_index")

    alter table(:inventory_materials) do
      remove :extra_description
      remove :quantity
      remove :color
      modify :unit, :text, null: false, default: nil
      add :sku, :text, null: false
      add :price, :decimal, null: false
      add :minimum_stock, :decimal
      add :maximum_stock, :decimal
    end
  end
end
