defmodule Craftplan.Repo.Migrations.SimplifyProductAndAddCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_products) do
      remove :nutrition_output_unit
      remove :nutrition_output_quantity
      remove :max_daily_quantity
      remove :sku
      remove :status
      add :category_id, :uuid
    end

    drop_if_exists unique_index(:catalog_products, [:sku], name: "catalog_products_sku_index")

    create table(:catalog_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:catalog_products) do
      modify :category_id,
             references(:catalog_categories,
               column: :id,
               name: "catalog_products_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalog_categories) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:catalog_categories, [:name], name: "catalog_categories_name_index")

    create unique_index(:catalog_categories, [:slug], name: "catalog_categories_slug_index")
  end

  def down do
    drop_if_exists unique_index(:catalog_categories, [:slug],
                     name: "catalog_categories_slug_index"
                   )

    drop_if_exists unique_index(:catalog_categories, [:name],
                     name: "catalog_categories_name_index"
                   )

    alter table(:catalog_categories) do
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:catalog_products, "catalog_products_category_id_fkey")

    alter table(:catalog_products) do
      modify :category_id, :uuid
    end

    drop table(:catalog_categories)

    create unique_index(:catalog_products, [:sku], name: "catalog_products_sku_index")

    alter table(:catalog_products) do
      remove :category_id
      add :status, :text, null: false, default: "draft"
      add :sku, :text, null: false
      add :max_daily_quantity, :bigint, null: false, default: 0
      add :nutrition_output_quantity, :decimal
      add :nutrition_output_unit, :text
    end
  end
end
