defmodule Craftplan.Repo.Migrations.SyncProductMaxDailyQuantity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_products) do
      add :max_daily_quantity, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:catalog_products) do
      remove :max_daily_quantity
    end
  end
end
