defmodule Craftplan.Repo.Migrations.AddCascadeDeleteToCustomer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:orders_orders, "orders_orders_customer_id_fkey")

    alter table(:orders_orders) do
      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "orders_orders_customer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:orders_orders, "orders_orders_customer_id_fkey")

    alter table(:orders_orders) do
      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "orders_orders_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
