defmodule Craftplan.Repo.Migrations.AllowDuplicateMaterialNames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:inventory_materials, [:name],
                     name: "inventory_materials_name_index"
                   )
  end

  def down do
    create unique_index(:inventory_materials, [:name], name: "inventory_materials_name_index")
  end
end
