defmodule Craftplan.Repo.Migrations.CascadeCustomerOrderItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:orders_items, "orders_items_order_id_fkey")

    alter table(:orders_items) do
      modify :order_id,
             references(:orders_orders,
               column: :id,
               name: "orders_items_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    alter table(:orders_item_lots) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_lots_order_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    alter table(:orders_item_batch_allocations) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_batch_allocations_order_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    alter table(:orders_item_batch_allocations) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_batch_allocations_order_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    alter table(:orders_item_lots) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_lots_order_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:orders_items, "orders_items_order_id_fkey")

    alter table(:orders_items) do
      modify :order_id,
             references(:orders_orders,
               column: :id,
               name: "orders_items_order_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
